bar/auction/models.py
from datetime import datetime

from bar import db

class AuctionPurchase(db.Model):
    __table_args__ = {'mysql_engine':'InnoDB'}
    id = db.Column(db.Integer, primary_key=True)
    participant_id = db.Column(db.Integer, db.ForeignKey('participant.id'), nullable=False)
    activity_id = db.Column(db.Integer, db.ForeignKey('activity.id'), nullable=False)
    description = db.Column(db.String(255), nullable=False)
    price = db.Column(db.Integer(), nullable=False)
    timestamp = db.Column(db.DateTime(), nullable=False)
    undone = db.Column(db.Boolean(), default=False, nullable=False)

    participant = db.relationship('Participant', backref=db.backref('auction_purchases', lazy='dynamic'))
    activity = db.relationship('Activity', backref=db.backref('auction_purchases', lazy='dynamic'))

    def __init__(self, **kwargs):
        self.timestamp = datetime.now()
        super(AuctionPurchase, self).__init__(**kwargs)

    def to_dict(self):
        exclude = ['timestamp']
        result = dict((field.name, getattr(self, field.name)) for field in self.__table__.columns if field.name not in exclude)
        result['timestamp'] = self.timestamp.isoformat()
        return result

bar/admin/forms.py
from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import TextField, BooleanField, validators

class ActivityForm(Form):
    name = TextField('Name', [validators.InputRequired(message='Name is required')])
    passcode = TextField('Passcode', [validators.InputRequired(message='Passcode is required')])
    active = BooleanField('Active')

class ImportForm(Form):
    import_file = FileField('Activity JSON', validators=[
        FileRequired(), 
        FileAllowed(['json'], 'JSON files only!')
        ])
    name = TextField('Name (optional)', validators=[
        validators.Optional(strip_whitespace=True)
        ])
    passcode = TextField('Passcode', validators=[
        validators.Optional(strip_whitespace=True)
        ])

bar/auction/forms.py
from flask_wtf import Form
from wtforms import TextField, IntegerField, validators

class AuctionForm(Form):
    description = TextField('Product description (optional)', validators=[
    	validators.Optional(strip_whitespace=True)
    ])
    price = IntegerField('Price (in Euro cent)', validators=[
    	validators.InputRequired(message='Price is required')
    ])
    participant = TextField('Participant', validators=[
    	validators.InputRequired(message='Participant is required')
    ])

bar/pos/forms.py
from validators import iban

from flask import current_app
from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import TextField, BooleanField, IntegerField, DateTimeField, RadioField, SelectField, validators, TextAreaField


class ExportForm(Form):
    pos = BooleanField('Consumptions')
    auction = BooleanField('Auction')
    description_pos_prefix = TextField('Consumption description prefix (optional)', [validators.Optional(strip_whitespace=True)])
    description_auction_prefix = TextField('Auction description prefix (optional)', [validators.Optional(strip_whitespace=True)])
    description = TextField('Description (optional)', [validators.Optional(strip_whitespace=True)])


class ParticipantForm(Form):
    name = TextField('Name', validators=[
        validators.InputRequired(message='Name is required')
    ])
    member_id = IntegerField('Member ID', validators=[
        validators.Optional(strip_whitespace=True)
    ])
    address = TextField('Address', [
        validators.InputRequired(message='Address is required')
    ])
    city = TextField('Place of residence', [
        validators.InputRequired(message='Place of residence is required')
    ])
    email = TextField('Email address', [
        validators.InputRequired(message='Email is required'),
        validators.Email(message='Invalid email address')
    ])
    iban = TextField('IBAN', [
        validators.InputRequired(message='IBAN is required')
    ])
    bic = TextField('BIC (optional)', [
        validators.Optional(strip_whitespace=True),
        validators.length(max=11, message='A BIC may not be longer than 11 characters')
    ])
    birthday  = DateTimeField('Date of birth (optional)', format='%Y-%m-%d', validators=[
        validators.Optional(strip_whitespace=True)
    ])
    barcode = TextField('Barcode', [
        validators.Optional(strip_whitespace=True),
        validators.length(max=255)
    ])

    def validate_iban(form, field):
        if field.raw_data[0] != current_app.config.get('NO_IBAN_STRING', 'OUTSIDE_SEPA_AREA') and (not iban(field.raw_data[0]) or len(field.raw_data[0]) > 34):
            raise validators.StopValidation('This is not a valid IBAN')


class RegistrationForm(Form):
    name = TextField('Name', [validators.InputRequired(message='Name is required')])
    birthday = DateTimeField('Birthday', format='%d-%m-%Y', validators=[
        validators.Optional(strip_whitespace=True)
    ])
    barcode = TextField('Barcode', [
        validators.Optional(strip_whitespace=True),
        validators.length(max=255)
    ])


class ProductForm(Form):
    name = TextField('Name', [validators.InputRequired(message='Name is required')])
    price = IntegerField('Price (in Euro cent)', [validators.InputRequired(message='Price is required')])
    priority = IntegerField('Priority (position of the button)', [validators.InputRequired(message='Priority is required')])
    age_limit = BooleanField('Age limit')


class ImportForm(Form):
    import_file = FileField('Participants CSV', validators=[FileRequired(), FileAllowed(['csv'], 'CSV files only!')])
    delimiter = SelectField('Delimiter', choices=[(';', ';'), (',', ',')])
    header = BooleanField('This file has a header')


class SettingsForm(Form):
    age_limit = IntegerField('Age limit (minimal legal age)', [validators.InputRequired(message='Age limit is required')])
    stacked_purchases = BooleanField('Allow stacked purchases (e.g. buy 6 beers at once)')
    require_terms = BooleanField('Accept terms before purchases')
    terms = TextAreaField('Terms', [validators.length(max=4096)])
    faq = TextAreaField('FAQ', [
        validators.Optional(strip_whitespace=True),
        validators.length(max=4096)
    ])
    uuid_prefix = TextField('UUID Prefix', [validators.length(max=255)])

    def validate_terms(form, field):
        if not form.require_terms.data:
            return
        if not field.raw_data or not field.raw_data[0]:
            field.errors[:] = []
            raise validators.StopValidation('Terms are required!')

bar/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_misaka import Misaka

from flask_coverapi import CoverSessionManager

# Init app
app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
migrate = Migrate(app, db)

md = Misaka(skip_html=True)
md.init_app(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'pos.login'

if not app.config.get('STAND_ALONE', False):
	cover_session_manager = CoverSessionManager(app.config['COVER_APP'], app.config['COVER_SECRET'], flask_app=app)

from .admin import admin
from .auction import auction
from .pos import pos

app.register_blueprint(admin)
app.register_blueprint(auction)
app.register_blueprint(pos)

from .pos.models import Activity

@login_manager.user_loader
def load_activity(activity_id):
    return Activity.query.get(activity_id)

from . import utils

bar/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, url_prefix='/admin')

from . import views

bar/admin/views.py
from __future__ import division

from functools import wraps

from flask import request, render_template, redirect, url_for, current_app, has_request_context, jsonify
from flask_login import login_user
from flask_coverapi import current_user

from datetime import datetime
import json
from sqlalchemy.exc import IntegrityError

from bar import db
from bar.pos.models import Activity, Product, Participant, Purchase
from bar.auction.models import AuctionPurchase

from . import admin
from .forms import ActivityForm, ImportForm


def admin_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if current_app.config.get('STAND_ALONE', False):
            return func(*args, **kwargs)
        elif not current_user.is_authenticated:
            return redirect(login_url())
        elif not current_user.is_admin:
            abort(403)
        return func(*args, **kwargs)
    return decorated_view


@admin.route('/', methods=['GET'])
@admin.route('/activities', methods=['GET'])
@admin_required
def list_activities():
    activities = Activity.query.all()
    return render_template('admin/activity_list.html', activities=activities)


@admin.route('/activities/add', methods=['GET', 'POST'])
@admin_required
def add_activity():
    """ Try to create a new activity. """
    form = ActivityForm()
    if form.validate_on_submit():
        activity = Activity(
            name=form.name.data, 
            passcode=form.passcode.data, 
            active=form.active.data
        )
        db.session.add(activity)
        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            form.passcode.errors.append('Please provide a unique passcode!')
            return render_template('activity_form.html', form=form, mode='add')
        else:
            return redirect(url_for('admin.list_activities'))
    return render_template('admin/activity_form.html', form=form, mode='add')


@admin.route('/activities/import', methods=['GET', 'POST'])
@admin_required
def import_activity():
    form = ImportForm()
    if form.validate_on_submit():
        try: 
            data = json.load(form.import_file.data)
            if not form.name.data:
                form.name.data = data['name']
            if not form.passcode.data:
                form.passcode.data = data['passcode']
            _load_activity(data, form.name.data, form.passcode.data)
        except IntegrityError:
            db.session.rollback()
            form.passcode.errors.append('Please provide a unique passcode!')
        except Exception as e:
            db.session.rollback()
            form.import_file.errors.append(str(e))
        else:
            return redirect(url_for('admin.list_activities'))
    return render_template('admin/activity_import_form.html', form=form)


def _load_activity(data, name=None, passcode=None):
    if not name:
        name = data['name']
    if not passcode:
        passcode = data['passcode']

    activity = Activity(
            name=name,
            passcode=passcode,
            **data['settings']
        )
    
    db.session.add(activity)
    db.session.flush()

    products = {}
    participants = {}

    for product in data['products']:
        p_id = str(product['id'])
        del product['id']
        product['activity_id'] = activity.id
        products[p_id] = Product(**product)
        db.session.add(products[p_id])

    for participant in data['participants']:
        p_id = str(participant['id'])
        del participant['id']
        if participant['birthday']:
            birthday = datetime.strptime(participant['birthday'], "%Y-%m-%dT%H:%M:%S"),
        else:
            birthday = None
        del participant['birthday']
        participant['activity_id'] = activity.id
        participants[p_id] = Participant(birthday=birthday, **participant)
        db.session.add(participants[p_id])

    db.session.flush()

    for purchase in data['pos_purchases']:
        p = Purchase(
            participant_id=participants[str(purchase['participant_id'])].id,
            activity_id=activity.id,
            product_id=products[str(purchase['product_id'])].id,
            timestamp=datetime.strptime(purchase['timestamp'], "%Y-%m-%dT%H:%M:%S"),
            undone=purchase['undone']
        )
        db.session.add(p)

    for purchase in data['auction_purchases']:
        p = AuctionPurchase(
            participant_id=participants[str(purchase['participant_id'])].id,
            activity_id=activity.id,
            description=purchase['description'],
            price=purchase['price'],
            timestamp=datetime.strptime(purchase['timestamp'], "%Y-%m-%dT%H:%M:%S"),
            undone=purchase['undone']
        )
        db.session.add(p)

    db.session.commit()


@admin.route('/activities/<int:activity_id>', methods=['GET', 'POST'])
@admin_required
def edit_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    form = ActivityForm(request.form, activity)
    if form.validate_on_submit():
        form.populate_obj(activity)
        try:
            db.session.commit()
        except IntegrityError:
            form.name.errors.append('Please provide a unique name!')
            return render_template('activity_form.html', form=form, mode='edit', id=activity.id)
        else:
            return redirect(url_for('admin.list_activities'))
    return render_template('admin/activity_form.html', form=form, mode='edit', id=activity.id)


@admin.route('/activities/<int:activity_id>/impersonate', methods=['GET', 'POST'])
@admin_required
def impersonate_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    login_user(activity, force=True)
    return redirect(url_for('pos.view_home'))


@admin.route('/activities/<int:activity_id>/activate', methods=['GET', 'POST'])
@admin_required
def activate_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    activity.active = request.args.get('activate') != 'False'
    db.session.commit()
    return redirect(url_for('admin.list_activities'))


@admin.route('/activities/<int:activity_id>/export.json', methods=['GET'])
@admin_required
def export_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    return jsonify(activity.to_dict())

bar/auction/__init__.py
from flask import Blueprint

auction = Blueprint('auction', __name__, url_prefix='/auction')

from . import views

bar/auction/views.py
from __future__ import division

from flask import request, render_template, redirect, url_for
from flask_login import login_required, current_user

from bar import db
from bar.pos.models import Participant

from . import auction
from .forms import AuctionForm
from .models import AuctionPurchase

@auction.route('/', methods=['GET', 'POST'])
@login_required
def list_auction():
    form = AuctionForm()
    if form.validate_on_submit():
        participant = Participant.query.filter_by(name=form.participant.data).first()
        purchase = AuctionPurchase(participant_id=participant.id, activity_id=current_user.id, description=form.description.data, price=form.price.data)
        db.session.add(purchase)
        db.session.commit()
        return redirect(url_for('auction.list_auction'))
    purchases = AuctionPurchase.query.filter_by(activity_id=current_user.get_id()).order_by(AuctionPurchase.timestamp.desc()).all()
    return render_template('auction/auction.html', form=form, purchases=purchases)


@auction.route('/purchases/<int:purchase_id>', methods=['GET', 'POST'])
@login_required
def edit_auction_purchase(purchase_id):
    """ Edit a purchase """
    purchase = AuctionPurchase.query.get_or_404(purchase_id)
    if purchase.activity_id != current_user.id:
        return 'Purchase not in current activity', 401
    form = AuctionForm(request.form, purchase)
    if form.validate_on_submit():
        participant = Participant.query.filter_by(name=form.participant.data).first()
        if participant:
            form.participant.data = participant
            form.populate_obj(purchase)
            db.session.commit()
            return redirect(url_for('auction.list_auction'))
        else:
            form.participant.errors.append('Participant not found!')
    else:
        form.participant.data = purchase.participant.name
    return render_template('auction/auction_form.html', form=form, mode='edit', id=purchase.id)


@auction.route('/purchases/<int:purchase_id>/undo', methods=['GET'])
@login_required
def undo_auction_purchase(purchase_id):
    purchase = AuctionPurchase.query.get_or_404(purchase_id)
    if purchase.activity_id != current_user.id:
        return 'Purchase not in current activity', 401    
    purchase.undone = request.args.get('undo') != 'False'
    db.session.commit()
    return redirect(url_for('auction.list_auction'))

bar/pos/__init__.py
from flask import Blueprint

pos = Blueprint('pos', __name__, url_prefix='')

from . import views

bar/templates/auction/auction.html
{% extends "base.html" %}

{% block page_id %}list-auction{% endblock %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/typeaheadjs.css') }}">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>{% block title %}Auction{% endblock %}</h1>
    <form method="post">
        {{ form.hidden_tag() }}
        <table class="table table-hover table-bar">
            <thead>
                <tr>
                    <th class="col-sm-2">Name</th>
                    <th class="col-sm-1">Price</th>
                    <th class="col-sm-3">Product description</th>
                    <th class="col-sm-1"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="{{ 'has-error' if form.participant.errors }}">
                        {{ form.participant.label(class="control-label sr-only") }}
                        {{ form.participant(class="form-control typeahead", autocomplete="off", placeholder=form.participant.label.text, autofocus="autofocus") }}
                    </td>
                    <td class="{{ 'has-error' if form.price.errors }}">
                        {{ form.price.label(class="control-label sr-only") }}
                        {{ form.price(class="form-control", placeholder=form.price.label.text) }}
                    </td>
                    <td class="{{ 'has-error' if form.description.errors }}">
                        {{ form.description.label(class="control-label sr-only") }}
                        {{ form.description(class="form-control", placeholder=form.description.label.text) }}
                    </td>
                    <td>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </td>
                </tr>
                {% for purchase in purchases %}
                <tr class="{{ 'danger' if purchase.undone }}">
                    <td>{{purchase.participant.name}}</td>
                    <td>{{format_price(purchase.price/100)}}</td>
                    <td>{{purchase.description}}</td>
                    <td>
                    {% if purchase.undone %}
                        <a href="{{url_for('auction.undo_auction_purchase', purchase_id=purchase.id, undo='False', next=request.url)}}" class="btn btn-default btn-sm">Redo</a>
                    {% else %}
                        <a href="{{url_for('auction.undo_auction_purchase', purchase_id=purchase.id, next=request.url)}}" class="btn btn-default btn-sm">Undo</a>
                    {% endif %}
                        <a href="{{ url_for('auction.edit_auction_purchase', purchase_id=purchase.id) }}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-pencil"></span></a>
                    </td>
                </tr> 
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock %}

{% block scripts %}
    {{super()}}
    <script src="{{ url_for('static', filename='js/typeahead.bundle.min.js') }}"></script>
    <script>
        var participants = new Bloodhound({ 
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace(['name', 'barcode']), 
            queryTokenizer: Bloodhound.tokenizers.whitespace, 
            identify: function(obj) { return obj.id; },
            prefetch: {
                url: '{{url_for('pos.list_participant_names')}}',
                cache: false
            }
        });

        $('#participant.typeahead').parent().on('keydown', function(evt){
            if(evt.key === 'Enter') {
                // Autocomplete when barcode is entered
                evt.preventDefault();
                $(".tt-suggestion:first-child", this).trigger('click');
            }
        });

        $('#participant.typeahead').typeahead({
            highlight: true
        }, { 
            name: 'participants',
            display: 'name',
            source: participants 
        });
    </script>
{% endblock %}

bar/templates/auction/auction_form.html
{% extends "base.html" %}

{% block page_id %}participant-add{% endblock %}

{% block css %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/typeaheadjs.css') }}">
{% endblock %}

{% block content %}
<div class="container-narrow">
    <h1>{% block title %}{{mode|title}} purchase{% endblock %}</h1>
    <form method="post" action="{{url_for('auction.edit_auction_purchase', purchase_id=id) }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.description.label(class="control-label") }}
            {{ form.description(class="form-control",autofocus="true") }}
        </div>
        {{ render_errors(form.description) }}
        <div class="form-group">
            {{ form.price.label(class="control-label") }}
            {{ form.price(class="form-control") }}
        </div>
        {{ render_errors(form.price) }}
        <div class="form-group">
            {{ form.participant.label(class="control-label") }}
            {{ form.participant(class="form-control typeahead", autocomplete="off") }}
        </div>
        {{ render_errors(form.participant) }}
    	<button type="submit" class="btn btn-primary">Submit</button>
        <a href="{{url_for('auction.list_auction')}}" class="btn btn-link">Cancel</a>
    </form>
</div>
{% endblock %}

{% block scripts %}
    {{super()}}
    <script src="{{ url_for('static', filename='js/typeahead.bundle.min.js') }}"></script>
    <script>
        var participants = new Bloodhound({ 
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'), 
            queryTokenizer: Bloodhound.tokenizers.whitespace, 
            identify: function(obj) { return obj.id; },
            prefetch: {
                url: '{{url_for('pos.list_participant_names')}}',
                cache: false
            }
        }); 

        $('#participant.typeahead').typeahead({
            highlight: true
        }, { 
            name: 'participants',
            display: 'name',
            source: participants 
        }); 
    </script>
{% endblock %}